version: '3.4'

services:
  sme.serap.prova.worker:
    image: ${DOCKER_REGISTRY-}smeserapprovaworker
    build:
      context: .
      dockerfile: src/SME.SERAp.Prova.Worker/Dockerfile
    networks:
      - sme-network    
networks:
  sme-network:
    external:
      name: sme-network
    driver: bridge